In [1]:
import numpy as np

In [2]:
type([1,2,3])

list

In [3]:
arr=np.array([1,2,3])

In [4]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(3,)

In [7]:
arr.size

3

In [8]:
arr.ndim

1

In [10]:
arr.dtype

dtype('int32')

In [11]:
arr1=[[1,2],[3,4]]

In [13]:
arr1=np.array(arr1)

In [14]:
arr1

array([[1, 2],
       [3, 4]])

In [15]:
arr1.shape

(2, 2)

In [16]:
arr1.dtype

dtype('int32')

In [17]:
arr1.size

4

In [18]:
arr1.ndim

2

In [19]:
#the above array is 2-dimensional

In [20]:
a=(1,2,3)

In [21]:
type(a)

tuple

In [22]:
a=np.array(a)

In [23]:
type(a)

numpy.ndarray

In [24]:
a.ndim

1

In [25]:
a.size

3

In [26]:
a.shape

(3,)

In [27]:
a.dtype

dtype('int32')

In [28]:
dict1={"firstname":"shabnam","lastname":"basheer"}

In [31]:
result=dict1.items()

In [32]:
data=list(result)

In [33]:
arr3=np.array(data)

In [34]:
arr3

array([['firstname', 'shabnam'],
       ['lastname', 'basheer']], dtype='<U9')

In [35]:
type(arr3)

numpy.ndarray

In [36]:
arr3.ndim

2

In [37]:
arr3.size

4

In [38]:
arr3.shape

(2, 2)

In [39]:
arr1

array([[1, 2],
       [3, 4]])

In [40]:
arr1[0]

array([1, 2])

In [41]:
arr1[0,1]

2

In [43]:
arr1[:,1]

array([2, 4])

In [44]:
arr1[0,:]

array([1, 2])

In [45]:
arr

array([1, 2, 3])

In [46]:
arr+2

array([3, 4, 5])

In [47]:
np.add(arr,2)

array([3, 4, 5])

In [50]:
np.subtract(arr,1)

array([0, 1, 2])

In [51]:
np.power(arr,2)

array([1, 4, 9], dtype=int32)

In [52]:
np.divide(arr,2)

array([0.5, 1. , 1.5])

In [53]:
li1=[1,2,3,4,5,6,600]

In [54]:
np.mean(li1)

88.71428571428571

In [55]:
np.median(li1)

4.0

In [56]:
np.std(li1)

208.73750726396898

In [57]:
np.var(li1)

43571.3469387755

In [58]:
np.quantile(li1,0.25)

2.5

In [59]:
np.quantile(li1,0.50)

4.0

In [60]:
np.linspace(3,10,10)

array([ 3.        ,  3.77777778,  4.55555556,  5.33333333,  6.11111111,
        6.88888889,  7.66666667,  8.44444444,  9.22222222, 10.        ])

In [61]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [62]:
np.arange(3,10,0.5)

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. ,
       9.5])

In [63]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [64]:
np.eye(3,3,)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [67]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [69]:
a=np.array([[1,2,3],[4,5,6,]])

In [70]:
type(a)

numpy.ndarray

In [71]:
a.shape

(2, 3)

In [72]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [73]:
a.reshape(3,2,order="F")

array([[1, 5],
       [4, 3],
       [2, 6]])

In [75]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [76]:
a.flatten(order="F")

array([1, 4, 2, 5, 3, 6])

In [77]:
np.ravel(a)

array([1, 2, 3, 4, 5, 6])

In [79]:
a=np.array([41,42,45,49,64,34,56,72,82])

In [80]:
np.where(a<50,a/2,a)

array([20.5, 21. , 22.5, 24.5, 64. , 17. , 56. , 72. , 82. ])